# Generated by Django 5.2.8 on 2025-11-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, help_text='Main complaint or diagnosis', max_length=200),
        ),
    ]
